options:
  formatter: stylish
  merge-default-rules: true
files:
  include: '**/*.sass'
rules:
  empty-line-between-blocks: 1
  variable-name-format: 0
  quotes: 0
  indentation: 0
  class-name-format: 0
  mixin-name-format: 0
  function-name-format: 0
  leading-zero: 0
  property-sort-order: 0
  force-pseudo-nesting: 0
  mixins-before-declarations: 0
  force-attribute-nesting: 0
  border-zero: 0
  no-duplicate-properties: 0
  no-mergeable-selectors: 0
  no-qualifying-elements: 0
  no-color-keywords: 0
  no-important: 0
  no-css-comments: 0
  no-vendor-prefixes: 0
  no-color-literals: 0
  no-warn: 0
  no-transition-all: 0
